# Generated by Django 5.2.8 on 2025-11-18 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('reunion_type', models.CharField(choices=[('education', 'Education Course'), ('project', 'Project Meeting'), ('revision', 'Revision with Classmates'), ('other', 'Other')], max_length=20)),
                ('subject', models.CharField(choices=[('math', 'Mathematics'), ('physics', 'Physics'), ('computer_science', 'Computer Science'), ('biology', 'Biology'), ('chemistry', 'Chemistry'), ('literature', 'Literature'), ('history', 'History'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(help_text='Brief title for the meeting', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Additional details about the meeting')),
                ('reminder_enabled', models.BooleanField(default=True, help_text='Enable reminders for this meeting')),
                ('reminder_timing', models.IntegerField(choices=[(5, '5 minutes before'), (15, '15 minutes before'), (30, '30 minutes before'), (60, '1 hour before'), (120, '2 hours before'), (1440, '1 day before'), (2880, '2 days before')], default=30, help_text='When to send reminder before the meeting')),
                ('reminder_sent', models.BooleanField(default=False, help_text='Whether reminder has been sent')),
                ('reminder_sent_at', models.DateTimeField(blank=True, help_text='When the reminder was sent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reunion',
                'verbose_name_plural': 'Reunions',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('reminder_type', models.CharField(default='scheduled', max_length=50)),
                ('sent_via', models.CharField(default='system', help_text='How the reminder was sent', max_length=50)),
                ('status', models.CharField(default='sent', help_text='sent, failed, etc.', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional information about the reminder')),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='Reunion.reunion')),
            ],
            options={
                'verbose_name': 'Reminder Log',
                'verbose_name_plural': 'Reminder Logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
