# Generated by Django 6.0 on 2025-12-04 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reunion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion',
            name='organizer',
            field=models.ForeignKey(blank=True, help_text='User who organized this meeting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_reunions', to=settings.AUTH_USER_MODEL),
        ),
    ]
