# Generated by Django 5.2.8 on 2025-12-10 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reunion', '0002_reunion_organizer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reminderlog',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_reunion_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reunion',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_reunions', to=settings.AUTH_USER_MODEL),
        ),
    ]
