# Generated by Django 5.2.8 on 2025-12-10 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reunion', '0003_reminderlog_user_reunion_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminderlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reunion',
            name='user',
        ),
    ]
