# Generated by Django 5.2 on 2025-11-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taches',
            fields=[
                ('idTache', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('dateEcheance', models.DateField()),
                ('statut', models.CharField(choices=[('A_FAIRE', 'À faire'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé')], default='EN_COURS', max_length=10)),
                ('resultat', models.CharField(choices=[('SUCCES', 'Succès'), ('ECHEC', 'Échec'), ('INDETERMINE', 'Indéterminé')], default='INDETERMINE', max_length=12)),
            ],
        ),
    ]
