# Generated by Django 5.2 on 2025-12-14 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Projects', '0003_notification'),
        ('Taches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taches',
            name='projet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='Gestion_Projects.project'),
        ),
    ]
